//
//  TestData.swift
//  RecessTestGrounds
//
//  Created by Torri Ray Porter Jr on 2023-03-29.
//

import Foundation
import SwiftUI
import FirebaseFirestore

class TestData: ObservableObject {
    @Published var users = usersData
    @Published var clubs = clubsData
    @Published var activities: [Activity] = []
    @Published var currentUser = usersData[0]
    @Published var loggedIn = false
    
    let activitiesRef = Firestore.firestore().collection("Activities")
    
    static let previewTestData = TestData(skipFetching: true)
    
    init(skipFetching: Bool = false) {
        if !skipFetching {
            getActivities()
        }
        print(mapLocations.count)
    }
    
    func getActivities() {
        activities = []
        activitiesRef.getDocuments() { querySnapshot, err in
            if let err = err {
                print("Error getting activity documents: \(err)")
            } else {
                for document in querySnapshot!.documents {
                    do {
                        let activity = try document.data(as: Activity.self)
                        //delete activity if it is older than 24 hours, else add to list
                        if Date.now.timeIntervalSince(activity.date) > 86400 {
                            self.activitiesRef.document(activity.id).delete()
                        } else {
                            self.activities.append(activity)
                        }
                    } catch {
                        print("Error decoding activity documents: \(error)")
                    }
                }
            }
        }
    }
}




var usersData: [User] = [
    User(name: "Temp User", email: "test@email.com", avatar: "3d_avatar_1")
]

var activitiesData: [Activity] = [
    Activity(title: "Blacktop basketball",
             sport: "Basketball",
             date: Date.now,
             description: "Casual game downtown. Come join the crew!",
             coordinates: [45.568978, -122.673523],
             creator: usersData[0].id)
]

var clubsData: [Club] = [
    Club(id: UUID().uuidString,
         creator: usersData[0].id,
         name: "Portland Blacktop",
         sport: "Basketball",
         members: [usersData[0].id],
         numActivities: 12,
         type: "Paid",
         description: "For Portlanders who are serious weekend warriors looking to improve their game")
]

var avatarStrings: [String] = [
    "3d_avatar_1",
    "3d_avatar_3",
    "3d_avatar_6",
    "3d_avatar_7",
    "3d_avatar_8",
    "3d_avatar_9",
    "3d_avatar_10",
    "3d_avatar_11",
    "3d_avatar_12",
    "3d_avatar_13",
    "3d_avatar_15",
    "3d_avatar_16",
    "3d_avatar_17",
    "3d_avatar_18",
    "3d_avatar_19",
    "3d_avatar_20",
    "3d_avatar_21",
    "3d_avatar_23",
    "3d_avatar_24",
    "3d_avatar_25",
    "3d_avatar_26",
    "3d_avatar_27",
    "3d_avatar_28",
    "3d_avatar_29",
    "3d_avatar_30",
]

var sportOptions: [String] = [
    "Baseball",
    "Basketball",
    "Football",
    "Rugby",
    "Soccer",
    "Spikeball",
    "Tennis",
    "Volleyball",
    "Other"
]

var mapLocations: [Location] = [
    Location(sport: "Basketball", name: "Irving Park", coordinates: [45.526198, -122.678870], notes: "2 half courts", address: "North Park Blocks 400–518 NW Park Ave Portland, OR  97209 United States", about: "In 2020, Portland Parks & Recreation and the Bureau of Environmental Services collaborated to create a nature patch to capture rainwater, foster wildlife habitat, and add natural features to enjoy. Several areas on the west side of Irving Park were converted to natural landscaping that include flowering native plants, stormwater swales, logs, boulders, split-rail fencing, and paths."),
    Location(sport: "Tennis", name: "Irving Park", coordinates: [45.546163, -122.657970], notes: "4 courts, lights are turned off at 9:30 PM, October 1-May 31, and at 10:00 PM, June 1-September 30.", address: "NE 7th Avenue and Fremont Street Portland, OR 97212", about: "In 2020, Portland Parks & Recreation and the Bureau of Environmental Services collaborated to create a nature patch to capture rainwater, foster wildlife habitat, and add natural features to enjoy. Several areas on the west side of Irving Park were converted to natural landscaping that include flowering native plants, stormwater swales, logs, boulders, split-rail fencing, and paths."),
    Location(sport: "Basktball", name: "Irving Park", coordinates: [45.547805, -122.657797], notes: "2 courts", address: "NE 7th Avenue and Fremont Street Portland, OR 97212", about: "In 2020, Portland Parks & Recreation and the Bureau of Environmental Services collaborated to create a nature patch to capture rainwater, foster wildlife habitat, and add natural features to enjoy. Several areas on the west side of Irving Park were converted to natural landscaping that include flowering native plants, stormwater swales, logs, boulders, split-rail fencing, and paths."),
    Location(sport: "Basktball", name: "Irving Park", coordinates: [45.547805, -122.657797], notes: "2 courts", address: "NE 7th Avenue and Fremont Street Portland, OR 97212", about: "In 2020, Portland Parks & Recreation and the Bureau of Environmental Services collaborated to create a nature patch to capture rainwater, foster wildlife habitat, and add natural features to enjoy. Several areas on the west side of Irving Park were converted to natural landscaping that include flowering native plants, stormwater swales, logs, boulders, split-rail fencing, and paths."),
    Location(sport: "Volleyball", name: "Irving Park", coordinates: [45.547128, -122.656774], notes: "", address: "NE 7th Avenue and Fremont Street Portland, OR 97212", about: "In 2020, Portland Parks & Recreation and the Bureau of Environmental Services collaborated to create a nature patch to capture rainwater, foster wildlife habitat, and add natural features to enjoy. Several areas on the west side of Irving Park were converted to natural landscaping that include flowering native plants, stormwater swales, logs, boulders, split-rail fencing, and paths."),
    Location(sport: "Soccer", name: "Irving Park", coordinates: [45.547128, -122.656774], notes: "2 possible pitches", address: "NE 7th Avenue and Fremont Street Portland, OR 97212", about: "In 2020, Portland Parks & Recreation and the Bureau of Environmental Services collaborated to create a nature patch to capture rainwater, foster wildlife habitat, and add natural features to enjoy. Several areas on the west side of Irving Park were converted to natural landscaping that include flowering native plants, stormwater swales, logs, boulders, split-rail fencing, and paths."),
    Location(sport: "Baseball", name: "Irving Park", coordinates: [45.547128, -122.656774], notes: "3 fields", address: "NE 7th Avenue and Fremont Street Portland, OR 97212", about: "In 2020, Portland Parks & Recreation and the Bureau of Environmental Services collaborated to create a nature patch to capture rainwater, foster wildlife habitat, and add natural features to enjoy. Several areas on the west side of Irving Park were converted to natural landscaping that include flowering native plants, stormwater swales, logs, boulders, split-rail fencing, and paths."),
    Location(sport: "Tennis", name: "Peninsula Park", coordinates: [45.569395, -122.672729], notes: "2 Tennis court lights are turned off at 10:00 PM. Park hours: 5:00am-midnight.", address: "700 N Rosa Parks Way Portland, OR 97217", about: "It includes the city's first public rose garden and first community center, a historically designated bandstand, and Portland's second oldest playground. "),
    Location(sport: "Basketball", name: "Peninsula Park", coordinates: [45.569149, -122.672733], notes: "Park hours: 5:00am-midnight.", address: "700 N Rosa Parks Way Portland, OR 97217", about: "It includes the city's first public rose garden and first community center, a historically designated bandstand, and Portland's second oldest playground. "),
    Location(sport: "Soccer", name: "Peninsula Park", coordinates: [45.568305, -122.673440], notes: "Park hours: 5:00am-midnight.", address: "700 N Rosa Parks Way Portland, OR 97217", about: "It includes the city's first public rose garden and first community center, a historically designated bandstand, and Portland's second oldest playground. "),
    Location(sport: "Baseball", name: "Peninsula Park", coordinates: [45.568305, -122.673440], notes: "Park hours: 5:00am-midnight.", address: "700 N Rosa Parks Way Portland, OR 97217", about: "It includes the city's first public rose garden and first community center, a historically designated bandstand, and Portland's second oldest playground. "),
    Location(sport: "Tennis", name: "Washington Park", coordinates: [45.519435, -122.706521], notes: "4 courts. Park hours: 5:00 am - 10:00 pm Closed to vehicles at 10:00 pm. To reserve a sports field, picnic area, or amphitheater, please call 503-823-2525.", address: "400 SW Kingston Avenue Portland, OR 97210", about: "Washington Park is the crown jewel of Portland. This 410-acre park is home to the Oregon Zoo, World Forestry Center, Hoyt Arboretum, International Rose Test Garden, and the Portland Japanese Garden,. Washington Park brings in 3.5 million visitors annually."),
    Location(sport: "Soccer", name: "Washington Park", coordinates: [45.519435, -122.706521], notes: "1 field. Park hours: 5:00 am - 10:00 pm Closed to vehicles at 10:00 pm. To reserve a sports field, picnic area, or amphitheater, please call 503-823-2525.", address: "400 SW Kingston Avenue Portland, OR 97210", about: "Washington Park is the crown jewel of Portland. This 410-acre park is home to the Oregon Zoo, World Forestry Center, Hoyt Arboretum, International Rose Test Garden, and the Portland Japanese Garden,. Washington Park brings in 3.5 million visitors annually."),
    Location(sport: "Soccer", name: "Laurelhurst Park", coordinates: [45.519815, -122.623816], notes: "Short field. Park hours: 5:00am-10:30pm", address: "SE Cesar E Chavez Blvd and Stark Street Portland, OR 97214", about: "Laurelhurst Park is a perfect example of the City Beautiful Movement in landscaping. In 1919, the park was named the most beautiful park on the west coast by the Pacific Coast Parks Association. Thanks to the efforts of the Portland Historical Landmarks Commission, in February 2001 Laurelhurst Park was named to the National Register of Historic Places."),
    Location(sport: "Basketball", name: "Laurelhurst Park", coordinates: [45.519487, -122.623438], notes: "1 full court, 2 half courts. Park hours: 5:00am-10:30pm", address: "SE Cesar E Chavez Blvd and Stark Street Portland, OR 97214", about: "Laurelhurst Park is a perfect example of the City Beautiful Movement in landscaping. In 1919, the park was named the most beautiful park on the west coast by the Pacific Coast Parks Association. Thanks to the efforts of the Portland Historical Landmarks Commission, in February 2001 Laurelhurst Park was named to the National Register of Historic Places."),
    Location(sport: "Tennis", name: "Laurelhurst Park", coordinates: [45.519956, -122.625452], notes: "2 lighted courts. Park hours: 5:00am-10:30pm", address: "SE Cesar E Chavez Blvd and Stark Street Portland, OR 97214", about: "Laurelhurst Park is a perfect example of the City Beautiful Movement in landscaping. In 1919, the park was named the most beautiful park on the west coast by the Pacific Coast Parks Association. Thanks to the efforts of the Portland Historical Landmarks Commission, in February 2001 Laurelhurst Park was named to the National Register of Historic Places."),
    Location(sport: "Volleyball", name: "Laurelhurst Park", coordinates: [45.519452, -122.624973], notes: "Park hours: 5:00am-10:30pm", address: "SE Cesar E Chavez Blvd and Stark Street Portland, OR 97214", about: "Laurelhurst Park is a perfect example of the City Beautiful Movement in landscaping. In 1919, the park was named the most beautiful park on the west coast by the Pacific Coast Parks Association. Thanks to the efforts of the Portland Historical Landmarks Commission, in February 2001 Laurelhurst Park was named to the National Register of Historic Places."),
    Location(sport: "Basketball", name: "Woodlawn Park", coordinates: [45.572109, -122.653881], notes: "1 court. Park hours: 5:00am-midnight", address: "NE 13th Avenue and Dekum Street Portland, OR 97211", about: "The seating wall near the playground was crafted by Portland artist Anne Storrs in 2000. The design of the Buckeye Bench was inspired by the Sweet buckeye tree that grows in the park. The cast forms resemble three views of the tree's leaves—a complete leaf, a close-up, and an even closer view of the leaves' ends."),
    Location(sport: "Soccer", name: "Woodlawn Park", coordinates: [45.573418, -122.652937], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "NE 13th Avenue and Dekum Street Portland, OR 97211", about: "The seating wall near the playground was crafted by Portland artist Anne Storrs in 2000. The design of the Buckeye Bench was inspired by the Sweet buckeye tree that grows in the park. The cast forms resemble three views of the tree's leaves—a complete leaf, a close-up, and an even closer view of the leaves' ends."),
    Location(sport: "Baseball", name: "Woodlawn Park", coordinates: [45.573418, -122.652937], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "NE 13th Avenue and Dekum Street Portland, OR 97211", about: "The seating wall near the playground was crafted by Portland artist Anne Storrs in 2000. The design of the Buckeye Bench was inspired by the Sweet buckeye tree that grows in the park. The cast forms resemble three views of the tree's leaves—a complete leaf, a close-up, and an even closer view of the leaves' ends."),
    Location(sport: "Baseball", name: "Alberta Park", coordinates: [45.565481, -122.645082], notes: "2 fields. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "NE 22nd Avenue and Killingsworth Street Portland, OR 97211", about: "An underutilized acre of grass under a stand of Douglas fir in the center of the park was converted in 2018 into a lush forest understory setting. The Alberta Park Nature Patch features forest plantings, nurse logs, root wads, boulders, and an accessible gravel path. These enhancements not only add beauty and natural elements to explore but improve habitat for birds and other native pollinators."),
    Location(sport: "Soccer",  name: "Alberta Park",coordinates: [45.565481, -122.645082], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "NE 22nd Avenue and Killingsworth Street Portland, OR 97211", about: "An underutilized acre of grass under a stand of Douglas fir in the center of the park was converted in 2018 into a lush forest understory setting. The Alberta Park Nature Patch features forest plantings, nurse logs, root wads, boulders, and an accessible gravel path. These enhancements not only add beauty and natural elements to explore but improve habitat for birds and other native pollinators."),
    Location(sport: "Basketball",  name: "Alberta Park",coordinates: [45.563736, -122.644912], notes: "1 covered court. Park hours: 5:00am-midnight.", address: "NE 22nd Avenue and Killingsworth Street Portland, OR 97211", about: "An underutilized acre of grass under a stand of Douglas fir in the center of the park was converted in 2018 into a lush forest understory setting. The Alberta Park Nature Patch features forest plantings, nurse logs, root wads, boulders, and an accessible gravel path. These enhancements not only add beauty and natural elements to explore but improve habitat for birds and other native pollinators."),
    Location(sport: "Tennis",  name: "Alberta Park",coordinates: [45.563596, -122.645790], notes: "1 court. Park hours: 5:00am-midnight.", address: "NE 22nd Avenue and Killingsworth Street Portland, OR 97211", about: "An underutilized acre of grass under a stand of Douglas fir in the center of the park was converted in 2018 into a lush forest understory setting. The Alberta Park Nature Patch features forest plantings, nurse logs, root wads, boulders, and an accessible gravel path. These enhancements not only add beauty and natural elements to explore but improve habitat for birds and other native pollinators."),
    Location(sport: "Soccer", name:"Arbor Lodge Park", coordinates: [45.572400, -122.693473], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.",  address: "N Bryant Street and Delaware Avenue Portland, OR 97217", about: "Created by artist Peter Helzer in 1996, Alligator and Otter is a small bronze statue of two animal characters fresh from a summer swim. A plaque with the artist's statement reads: \"This sculpture is for all who enjoy the simple pleasures of a beautiful Oregon day. May it serve to remind us of good friends, good times, and good memories.\" The sculpture was relocated with the Harper’s Playground project to a new boulder home by the sand and water play area."),
    Location(sport: "Baseball",  name:"Arbor Lodge Park",coordinates: [45.572400, -122.693473], notes: "2 fields. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "N Bryant Street and Delaware Avenue Portland, OR 97217", about: "Created by artist Peter Helzer in 1996, Alligator and Otter is a small bronze statue of two animal characters fresh from a summer swim. A plaque with the artist's statement reads: \"This sculpture is for all who enjoy the simple pleasures of a beautiful Oregon day. May it serve to remind us of good friends, good times, and good memories.\" The sculpture was relocated with the Harper’s Playground project to a new boulder home by the sand and water play area."),
    Location(sport: "Tennis",  name:"Arbor Lodge Park",coordinates: [45.573213, -122.693713], notes: "2 lighted courts. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "N Bryant Street and Delaware Avenue Portland, OR 97217", about: "Created by artist Peter Helzer in 1996, Alligator and Otter is a small bronze statue of two animal characters fresh from a summer swim. A plaque with the artist's statement reads: \"This sculpture is for all who enjoy the simple pleasures of a beautiful Oregon day. May it serve to remind us of good friends, good times, and good memories.\" The sculpture was relocated with the Harper’s Playground project to a new boulder home by the sand and water play area."),
    Location(sport: "Soccer", name: "Argay Park", coordinates: [45.552234, -122.518397], notes: "1 field. Park hours: 5:00am-midnight. No parking on park side of street after 10:00pm. To reserve a sports field, call 503-823-2525.", address: "NE 141st Avenue and Failing Street Portland, OR 97230", about: "In 2017, Argay Park’s tennis court was fully renovated with funding from the 2014 Parks Replacement Bond. Improvements included: ADA accessibility on the pathway from NE 141st Avenue to the tennis courts; rebuilt playing surface to eliminate cracking and differential settlement; replacement of fencing, nets, drinking fountain, wood planking on benches, and the stanchions; installment of a stormwater facility to address runoff; and upgraded lighting. Based on community input from Argay neighbors, PP&R removed a large grove of holly trees to improve safety and sightlines, but kept four of the holly trees - two green and two variegated - to preserve the history of the site and neighborhood."),
    Location(sport: "Baseball", name: "Argay Park", coordinates: [45.552234, -122.518397], notes: "Park hours: 5:00am-midnight. No parking on park side of street after 10:00pm. To reserve a sports field, call 503-823-2525.", address: "NE 141st Avenue and Failing Street Portland, OR 97230", about: "In 2017, Argay Park’s tennis court was fully renovated with funding from the 2014 Parks Replacement Bond. Improvements included: ADA accessibility on the pathway from NE 141st Avenue to the tennis courts; rebuilt playing surface to eliminate cracking and differential settlement; replacement of fencing, nets, drinking fountain, wood planking on benches, and the stanchions; installment of a stormwater facility to address runoff; and upgraded lighting. Based on community input from Argay neighbors, PP&R removed a large grove of holly trees to improve safety and sightlines, but kept four of the holly trees - two green and two variegated - to preserve the history of the site and neighborhood."),
    Location(sport: "Basketball", name: "Argay Park", coordinates: [45.551535, -122.519229], notes: "1 full court, 1 half court. Park hours: 5:00am-midnight. No parking on park side of street after 10:00pm", address: "NE 141st Avenue and Failing Street Portland, OR 97230", about: "In 2017, Argay Park’s tennis court was fully renovated with funding from the 2014 Parks Replacement Bond. Improvements included: ADA accessibility on the pathway from NE 141st Avenue to the tennis courts; rebuilt playing surface to eliminate cracking and differential settlement; replacement of fencing, nets, drinking fountain, wood planking on benches, and the stanchions; installment of a stormwater facility to address runoff; and upgraded lighting. Based on community input from Argay neighbors, PP&R removed a large grove of holly trees to improve safety and sightlines, but kept four of the holly trees - two green and two variegated - to preserve the history of the site and neighborhood."),
    Location(sport: "Tennis", name: "Argay Park", coordinates: [45.551535, -122.519229], notes: "4 lighted courts. Park hours: 5:00am-midnight. No parking on park side of street after 10:00pm.", address: "NE 141st Avenue and Failing Street Portland, OR 97230", about: "In 2017, Argay Park’s tennis court was fully renovated with funding from the 2014 Parks Replacement Bond. Improvements included: ADA accessibility on the pathway from NE 141st Avenue to the tennis courts; rebuilt playing surface to eliminate cracking and differential settlement; replacement of fencing, nets, drinking fountain, wood planking on benches, and the stanchions; installment of a stormwater facility to address runoff; and upgraded lighting. Based on community input from Argay neighbors, PP&R removed a large grove of holly trees to improve safety and sightlines, but kept four of the holly trees - two green and two variegated - to preserve the history of the site and neighborhood."),
    Location(sport: "Baseball", name: "Berkeley Park", coordinates: [45.473373, -122.623280], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, please call 503-823-2525.", address: "3701 SE Bybee Blvd Portland, OR 97202 United States", about: "Dedicated on July 27, 2014, the Alex Rovello Memorial Courts are the result of the efforts of Alex’s parents, Geri and Jim Rovello, who lost their son in a tragic accident in spring 2013. Alex learned to play tennis at the age of two at Berkeley Park. He went on to win four state singles titles, was a member of Cleveland High School’s only state championship team, and was a nationally ranked Junior Player in the USTA as well as an outstanding player at the University of Oregon. Berkeley Park had two neglected but well-loved courts that have now been renovated to USTA standards. Through generous contributions to the Alex Rovello Memorial Fund, these courts are a fitting tribute to Alex."),
    Location(sport: "Soccer", name: "Berkeley Park", coordinates: [45.473373, -122.623280], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, please call 503-823-2525.", address: "3701 SE Bybee Blvd Portland, OR 97202 United States", about: "Dedicated on July 27, 2014, the Alex Rovello Memorial Courts are the result of the efforts of Alex’s parents, Geri and Jim Rovello, who lost their son in a tragic accident in spring 2013. Alex learned to play tennis at the age of two at Berkeley Park. He went on to win four state singles titles, was a member of Cleveland High School’s only state championship team, and was a nationally ranked Junior Player in the USTA as well as an outstanding player at the University of Oregon. Berkeley Park had two neglected but well-loved courts that have now been renovated to USTA standards. Through generous contributions to the Alex Rovello Memorial Fund, these courts are a fitting tribute to Alex."),
    Location(sport: "Tennis", name: "Berkeley Park", coordinates: [45.472703, -122.623059], notes: "2 lighted courts. Park hours: 5:00am-midnight. To reserve a sports field, please call 503-823-2525.", address: "3701 SE Bybee Blvd Portland, OR 97202 United States", about: "Dedicated on July 27, 2014, the Alex Rovello Memorial Courts are the result of the efforts of Alex’s parents, Geri and Jim Rovello, who lost their son in a tragic accident in spring 2013. Alex learned to play tennis at the age of two at Berkeley Park. He went on to win four state singles titles, was a member of Cleveland High School’s only state championship team, and was a nationally ranked Junior Player in the USTA as well as an outstanding player at the University of Oregon. Berkeley Park had two neglected but well-loved courts that have now been renovated to USTA standards. Through generous contributions to the Alex Rovello Memorial Fund, these courts are a fitting tribute to Alex."),
    Location(sport: "Baseball", name: "Bloomington Park", coordinates: [45.485858, -122.559754], notes: "2 fields. Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "SE Steele St & SE 100th Ave Portland, OR  97266 United States", about: "In 2017-2018, Bloomington Park’s restrooms were renovated, and a new musical play piece was added to the playground with funding from the 2014 Parks Replacement Bond. Improvements included the addition of an ADA pathway and an ADA reserved parking space on SE Steele Street."),
    Location(sport: "Soccer", name: "Bloomington Park", coordinates: [45.484635, -122.559976], notes: "1 pitch. Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "SE Steele St & SE 100th Ave Portland, OR  97266 United States", about: "In 2017-2018, Bloomington Park’s restrooms were renovated, and a new musical play piece was added to the playground with funding from the 2014 Parks Replacement Bond. Improvements included the addition of an ADA pathway and an ADA reserved parking space on SE Steele Street."),
    Location(sport: "Basketball", name: "Bloomington Park", coordinates: [45.485206, -122.559351], notes: "1 full court. Park hours: 5:00am-midnight.", address: "SE Steele St & SE 100th Ave Portland, OR  97266 United States", about: "In 2017-2018, Bloomington Park’s restrooms were renovated, and a new musical play piece was added to the playground with funding from the 2014 Parks Replacement Bond. Improvements included the addition of an ADA pathway and an ADA reserved parking space on SE Steele Street."),
    Location(sport: "Volleyball", name: "Brentwood Park", coordinates: [45.473448, -122.601778], notes: "2 courts. Park hours: 5:00am-midnight.", address: "6434 SE 60th Ave Portland, OR  97206 United States", about: ""),
    Location(sport: "Baseball", name: "Brentwood Park", coordinates: [45.473484, -122.600823], notes: "1 field. Park hours: 5:00am-midnight.", address: "6434 SE 60th Ave Portland, OR  97206 United States", about: ""),
    Location(sport: "Soccer", name: "Brentwood Park", coordinates: [45.473484, -122.600823], notes: "1 field. Park hours: 5:00am-midnight.", address: "6434 SE 60th Ave Portland, OR  97206 United States", about: ""),
    Location(sport: "Basketball", name: "Brooklyn Park", coordinates: [45.498846, -122.655126], notes: "1 full court. Street parking", address: "Brooklyn Park 3400 SE Milwaukie Ave Portland, OR  97202 United States", about: "Three large golden granite boulders, situated near the play area, were sculpted into heads by California artist Marcia Donahue. The boulders, each weighing approximately 2-3 tons, were hand-picked by the artist at a ranch near Bakersfield, CA. The sculpture is aptly named Tête à Tête à Tête and serves as the permanent audience for baseball games as well as a gathering place for park visitors. The sculpture was installed in 1996."),
    Location(sport: "Baseball", name: "Brooklyn Park", coordinates: [45.498660, -122.654690], notes: "1 field. To reserve a sports field, call 503-823-2525. Street parking", address: "Brooklyn Park 3400 SE Milwaukie Ave Portland, OR  97202 United States", about: "Three large golden granite boulders, situated near the play area, were sculpted into heads by California artist Marcia Donahue. The boulders, each weighing approximately 2-3 tons, were hand-picked by the artist at a ranch near Bakersfield, CA. The sculpture is aptly named Tête à Tête à Tête and serves as the permanent audience for baseball games as well as a gathering place for park visitors. The sculpture was installed in 1996."),
    Location(sport: "Basketball", name: "Clinton Park", coordinates: [45.504396, -122.605067], notes: "2 courts. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "2905 SE 55th Ave Portland, OR  97206 United States", about: "Clinton Park is named after Clinton Street which abuts the park. Clinton Street is named for a popular pioneer minister, the Rev. Clinton Kelly. Kelly's brother, the Rev. Albert Kelly, has a park in southwest Portland as his namesake (Albert Kelly Park)."),
    Location(sport: "Baseball", name: "Clinton Park", coordinates: [45.503625, -122.605116], notes: "2 fields. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "2905 SE 55th Ave Portland, OR  97206 United States", about: "Clinton Park is named after Clinton Street which abuts the park. Clinton Street is named for a popular pioneer minister, the Rev. Clinton Kelly. Kelly's brother, the Rev. Albert Kelly, has a park in southwest Portland as his namesake (Albert Kelly Park)."),
    Location(sport: "Soccer", name: "Clinton Park", coordinates: [45.503625, -122.605116], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "2905 SE 55th Ave Portland, OR  97206 United States", about: "Clinton Park is named after Clinton Street which abuts the park. Clinton Street is named for a popular pioneer minister, the Rev. Clinton Kelly. Kelly's brother, the Rev. Albert Kelly, has a park in southwest Portland as his namesake (Albert Kelly Park)."),
    Location(sport: "Baseball", name:"Colonel Summers Park", coordinates: [45.515524, -122.646712], notes: " 1 field. Park hours: 5:00am-10:00pm. To reserve a sports field, please call 503-823-2525", address: "1925 SE Taylor St Portland, OR  97214 United States", about: "In 2017, Colonel Summers Park received several major improvements. A decorative picnic shelter enclosure, new splash pad, and picnic tables were installed thanks to System Development Charge funds. Funding from the 2014 Parks Replacement Bond provided a Portland Loo and removal of ADA barriers on the pathway from SE Taylor Street to the picnic shelter."),
    Location(sport: "Volleyball", name:"Colonel Summers Park", coordinates: [45.515524, -122.646712], notes: "Park hours: 5:00am-10:00pm", address: "1925 SE Taylor St Portland, OR  97214 United States", about: "In 2017, Colonel Summers Park received several major improvements. A decorative picnic shelter enclosure, new splash pad, and picnic tables were installed thanks to System Development Charge funds. Funding from the 2014 Parks Replacement Bond provided a Portland Loo and removal of ADA barriers on the pathway from SE Taylor Street to the picnic shelter."),
    Location(sport: "Basketball", name:"Colonel Summers Park", coordinates: [45.515371, -122.648201], notes: "1 court. Park hours: 5:00am-10:00pm", address: "1925 SE Taylor St Portland, OR  97214 United States", about: "In 2017, Colonel Summers Park received several major improvements. A decorative picnic shelter enclosure, new splash pad, and picnic tables were installed thanks to System Development Charge funds. Funding from the 2014 Parks Replacement Bond provided a Portland Loo and removal of ADA barriers on the pathway from SE Taylor Street to the picnic shelter."),
    Location(sport: "Tennis", name:"Colonel Summers Park", coordinates: [45.516145, -122.646788], notes: "2 courts. Park hours: 5:00am-10:00pm", address: "1925 SE Taylor St Portland, OR  97214 United States", about: "In 2017, Colonel Summers Park received several major improvements. A decorative picnic shelter enclosure, new splash pad, and picnic tables were installed thanks to System Development Charge funds. Funding from the 2014 Parks Replacement Bond provided a Portland Loo and removal of ADA barriers on the pathway from SE Taylor Street to the picnic shelter."),
    Location(sport: "Volleyball", name: "Columbia Park", coordinates: [45.579415, -122.710805], notes: "Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "N Lombard Street and Woolsey Avenue Portland, OR 97203 United States", about: "At just over 35 acres, Columbia Park and Annex houses mature Douglas-firs and lindens, sports fields, and a historic cottage, serving as an important shared community space for North Portlanders. Columbia Annex is located directly across North Lombard Street from Columbia Park."),
    Location(sport: "Tennis", name: "Columbia Park", coordinates: [45.580303, -122.709529], notes: "2 lighted courts. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "N Lombard Street and Woolsey Avenue Portland, OR 97203 United States", about: "At just over 35 acres, Columbia Park and Annex houses mature Douglas-firs and lindens, sports fields, and a historic cottage, serving as an important shared community space for North Portlanders. Columbia Annex is located directly across North Lombard Street from Columbia Park."),
    Location(sport: "Baseball", name: "Columbia Park", coordinates: [45.579415, -122.710805], notes: "4 fields. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "N Lombard Street and Woolsey Avenue Portland, OR 97203 United States", about: "At just over 35 acres, Columbia Park and Annex houses mature Douglas-firs and lindens, sports fields, and a historic cottage, serving as an important shared community space for North Portlanders. Columbia Annex is located directly across North Lombard Street from Columbia Park."),
    Location(sport: "Soccer", name: "Columbia Park", coordinates: [45.579415, -122.710805], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "N Lombard Street and Woolsey Avenue Portland, OR 97203 United States", about: "At just over 35 acres, Columbia Park and Annex houses mature Douglas-firs and lindens, sports fields, and a historic cottage, serving as an important shared community space for North Portlanders. Columbia Annex is located directly across North Lombard Street from Columbia Park."),
    Location(sport: "Football", name: "Columbia Park", coordinates: [45.579415, -122.710805], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "N Lombard Street and Woolsey Avenue Portland, OR 97203 United States", about: "At just over 35 acres, Columbia Park and Annex houses mature Douglas-firs and lindens, sports fields, and a historic cottage, serving as an important shared community space for North Portlanders. Columbia Annex is located directly across North Lombard Street from Columbia Park."),
    Location(sport: "Tennis", name: "Creston Park", coordinates: [45.496701, -122.615507], notes: "Park hours: 5:00am-10:00pm", address: "SE 44th Avenue and Powell Blvd Portland, OR 97206", about: "One of the new wave of multi-use neighborhood parks during the City Beautiful movement, this property became a park due to a bond issue for parks and playground expansion approved by voters in 1919. The natatorium (swim facility) was construced in 1925 along with two brick comfort stations. By 1926, tennis courts, horseshoe pits, and a ball field were added."),
    Location(sport: "Soccer", name: "Delta Park", coordinates: [45.597142, -122.680953], notes: "9 full size soccer pitches. Park hours: 6:00am-10:00pm. To reserve a sports field, call 503-643-1530.", address: "10850 N Denver Ave Portland, OR 97217 United States", about: "Delta Park and the Portland International Raceway were built on the site of the city of Vanport City, which was destroyed by a flood in 1948. Prior to its destruction, Vanport was the second largest city in Oregon. Vanport was constructed in order to house the thousands of war-time shipbuilders that Henry Kaiser, of Henry Kaiser Industries, had recruited from New York to help with the war effort. Vanport, which was constructed in under a year, was deemed 'The Miracle City.' It had its own post office, nine schools, a fire station, a 400-seat cafeteria, a 785-seat theater, a library, a hospital, fourteen playgrounds, five commercial centers, and a police station staffed by twenty-two officers."),
    Location(sport: "Baseball", name: "Delta Park", coordinates: [45.599835, -122.679385], notes: "7 fields. Park hours: 6:00am-10:00pm. To reserve a sports field, call 503-643-1530.", address: "10850 N Denver Ave Portland, OR 97217 United States", about: "Delta Park and the Portland International Raceway were built on the site of the city of Vanport City, which was destroyed by a flood in 1948. Prior to its destruction, Vanport was the second largest city in Oregon. Vanport was constructed in order to house the thousands of war-time shipbuilders that Henry Kaiser, of Henry Kaiser Industries, had recruited from New York to help with the war effort. Vanport, which was constructed in under a year, was deemed 'The Miracle City.' It had its own post office, nine schools, a fire station, a 400-seat cafeteria, a 785-seat theater, a library, a hospital, fourteen playgrounds, five commercial centers, and a police station staffed by twenty-two officers."),
    Location(sport: "Volleyball", name: "Delta Park", coordinates: [45.598823, -122.676207], notes: "6 courts. Park hours: 6:00am-10:00pm. To reserve a sports field, call 503-643-1530.", address: "10850 N Denver Ave Portland, OR 97217 United States", about: "Delta Park and the Portland International Raceway were built on the site of the city of Vanport City, which was destroyed by a flood in 1948. Prior to its destruction, Vanport was the second largest city in Oregon. Vanport was constructed in order to house the thousands of war-time shipbuilders that Henry Kaiser, of Henry Kaiser Industries, had recruited from New York to help with the war effort. Vanport, which was constructed in under a year, was deemed 'The Miracle City.' It had its own post office, nine schools, a fire station, a 400-seat cafeteria, a 785-seat theater, a library, a hospital, fourteen playgrounds, five commercial centers, and a police station staffed by twenty-two officers."),
    Location(sport: "Basketball", name: "Dr. MLK Jr School Park", coordinates: [45.557494, -122.659729], notes: "1 court. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "NE 6th Avenue and Humboldt Street Portland, OR 97211", about: "In 1968, Highland School’s name was changed to Dr. Martin Luther King, Jr. School, just weeks after Dr. King’s assassination. The effort was student-led and was formally recognized by a visit by Senator Edward Kennedy and dedication ceremony on May 9, 1968. When the adjacent park opened in 1979, it took on the name of King School Park. In 2022, the park name was formally corrected to Dr. Martin Luther King Jr. School Park to align the name of the park with the school and properly honor Dr. King by using his honorific."),
    Location(sport: "Soccer", name: "Dr. MLK Jr School Park", coordinates: [45.556819, -122.660006], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "NE 6th Avenue and Humboldt Street Portland, OR 97211", about: "In 1968, Highland School’s name was changed to Dr. Martin Luther King, Jr. School, just weeks after Dr. King’s assassination. The effort was student-led and was formally recognized by a visit by Senator Edward Kennedy and dedication ceremony on May 9, 1968. When the adjacent park opened in 1979, it took on the name of King School Park. In 2022, the park name was formally corrected to Dr. Martin Luther King Jr. School Park to align the name of the park with the school and properly honor Dr. King by using his honorific."),
    Location(sport: "Baseball", name: "Dr. MLK Jr School Park", coordinates: [45.556819, -122.660006], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "NE 6th Avenue and Humboldt Street Portland, OR 97211", about: "In 1968, Highland School’s name was changed to Dr. Martin Luther King, Jr. School, just weeks after Dr. King’s assassination. The effort was student-led and was formally recognized by a visit by Senator Edward Kennedy and dedication ceremony on May 9, 1968. When the adjacent park opened in 1979, it took on the name of King School Park. In 2022, the park name was formally corrected to Dr. Martin Luther King Jr. School Park to align the name of the park with the school and properly honor Dr. King by using his honorific."),
    Location(sport: "Basketball", name: "Ed Benedict Park", coordinates: [45.495179, -122.557975], notes: "1 court. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "100th SE Avenue and Powell Blvd Portland, OR 97266 United States", about: "The park was named in commemoration of Ed Benedict, a statesman and community activist who was instrumental in getting the park built. In addition to his work as a nurseryman and landscape contractor, he served three terms in the Oregon Legislature, and was a member of many community organizations, including Urban League of Portland, NAACP, and the East County Coordinating Committee. When the proposed Mt. Hood freeway project fell through, Benedict worked hard to ensure that the land that had been purchased as an easement for the freeway be developed as a neighborhood park. In 1988 the parcel known as Mt Hood Park was deeded to the City of Portland for \"eventual use as a recreational park.\" Benedict died that year and, in his will, left money to establish a trust fund to develop the park. Ed Benedict Community Park was officially named at a ceremony on July 29, 1991."),
    Location(sport: "Soccer", name: "Ed Benedict Park", coordinates: [45.495179, -122.557975], notes: "2 fields. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "100th SE Avenue and Powell Blvd Portland, OR 97266 United States", about: "The park was named in commemoration of Ed Benedict, a statesman and community activist who was instrumental in getting the park built. In addition to his work as a nurseryman and landscape contractor, he served three terms in the Oregon Legislature, and was a member of many community organizations, including Urban League of Portland, NAACP, and the East County Coordinating Committee. When the proposed Mt. Hood freeway project fell through, Benedict worked hard to ensure that the land that had been purchased as an easement for the freeway be developed as a neighborhood park. In 1988 the parcel known as Mt Hood Park was deeded to the City of Portland for \"eventual use as a recreational park.\" Benedict died that year and, in his will, left money to establish a trust fund to develop the park. Ed Benedict Community Park was officially named at a ceremony on July 29, 1991."),
    Location(sport: "Tennis", name: "Essex park", coordinates: [45.494158, -122.584336], notes: "2 lighted courts. Park hours: 5:00am-midnight.", address: "SE 79th Avenue and Center Street Portland, OR 97206 United States", about: ""),
    Location(sport: "Baseball", name: "Essex park", coordinates: [45.494206, -122.583251], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SE 79th Avenue and Center Street Portland, OR 97206 United States", about: ""),
    Location(sport: "Basketball", name: "Essex park", coordinates: [45.494381, -122.584319], notes: "1 court. Park hours: 5:00am-midnight.", address: "SE 79th Avenue and Center Street Portland, OR 97206 United States", about: ""),
    Location(sport: "Baseball", name: "Fernhill Park", coordinates: [45.565998, -122.623550], notes: "2 fields. Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "NE 37th Avenue and Ainsworth Street Portland, OR 97211 United States", about: "According to rumor, the land that is now called Fernhill Park was used as a dumping ground for stolen cars. Auto thieves would steal cars, take them to the ravine, and strip them down for parts. Portland Parks & Recreation 'rode to the rescue' and removed briar patches, graded the hills, and planted grass – turning this one-time valley of vandals into a beautiful park for everyone to enjoy!"),
    Location(sport: "Soccer", name: "Fernhill Park", coordinates: [45.565998, -122.623550], notes: "1 pitch. Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "NE 37th Avenue and Ainsworth Street Portland, OR 97211 United States", about: "According to rumor, the land that is now called Fernhill Park was used as a dumping ground for stolen cars. Auto thieves would steal cars, take them to the ravine, and strip them down for parts. Portland Parks & Recreation 'rode to the rescue' and removed briar patches, graded the hills, and planted grass – turning this one-time valley of vandals into a beautiful park for everyone to enjoy!"),
    Location(sport: "Tennis", name: "Fernhill Park", coordinates: [45.565998, -122.623550], notes: "2 tennis courts. Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "NE 37th Avenue and Ainsworth Street Portland, OR 97211 United States", about: "According to rumor, the land that is now called Fernhill Park was used as a dumping ground for stolen cars. Auto thieves would steal cars, take them to the ravine, and strip them down for parts. Portland Parks & Recreation 'rode to the rescue' and removed briar patches, graded the hills, and planted grass – turning this one-time valley of vandals into a beautiful park for everyone to enjoy!"),
    Location(sport: "Volleyball", name: "Gabriel Park", coordinates: [45.474188, -122.720975], notes: "Park hours: 5:00am-midnight. Parking lot off SW Canby closed at 10:00pm. To reserve a sports field or picnic area, call 503-823-2525", address: "SW 45th Ave & Vermont St Portland, OR 97219 United States", about: ""),
    Location(sport: "Tennis", name: "Gabriel Park", coordinates: [45.473575, -122.721608], notes: "8 courts. Park hours: 5:00am-midnight. Parking lot off SW Canby closed at 10:00pm. To reserve a sports field or picnic area, call 503-823-2525", address: "SW 45th Ave & Vermont St Portland, OR 97219 United States", about: ""),
    Location(sport: "Baseball", name: "Gabriel Park", coordinates: [45.474308, -122.717972], notes: "4 fields. Park hours: 5:00am-midnight. Parking lot off SW Canby closed at 10:00pm. To reserve a sports field, call 503-823-2525", address: "SW 45th Ave & Vermont St Portland, OR 97219 United States", about: ""),
    Location(sport: "Basketball", name: "Gabriel Park", coordinates: [45.475246, -122.716622], notes: "1 court. Park hours: 5:00am-midnight. Parking lot off SW Canby closed at 10:00pm.", address: "SW 45th Ave & Vermont St Portland, OR 97219 United States", about: ""),
    Location(sport: "Tennis", name: "Grant Park", coordinates: [45.539691, -122.629325], notes: "6 lighted courts. Park hours: 5:00am-midnight. To reserve a sports field call 503-823-2525.", address: "NE 33rd Avenue and US Grant Place Portland, OR 97212 United States", about: "Grant Park was the setting for many scenes in children's books by Beverly Cleary. In 1991, a group of teachers, librarians, and business people formed the Friends of Henry & Ramona, and began to raise funds for the Beverly Cleary Sculpture Garden for Children. Portland artist Lee Hunt created life-sized bronze statues of three of Cleary's best-loved characters - Ramona Quimby, Henry Huggins, and Henry's dog Ribsy. Scattered around the concrete slab are granite plaques engraved with the titles of the Cleary books that take place in Portland - and a map of the neighborhood showing where events in the books \"really happened.\" The Sculpture Garden was dedicated on October 13, 1995."),
    Location(sport: "Basketball", name: "Grant Park", coordinates: [45.540200, -122.627926], notes: "1 full court. Park hours: 5:00am-midnight.", address: "NE 33rd Avenue and US Grant Place Portland, OR 97212 United States", about: "Grant Park was the setting for many scenes in children's books by Beverly Cleary. In 1991, a group of teachers, librarians, and business people formed the Friends of Henry & Ramona, and began to raise funds for the Beverly Cleary Sculpture Garden for Children. Portland artist Lee Hunt created life-sized bronze statues of three of Cleary's best-loved characters - Ramona Quimby, Henry Huggins, and Henry's dog Ribsy. Scattered around the concrete slab are granite plaques engraved with the titles of the Cleary books that take place in Portland - and a map of the neighborhood showing where events in the books \"really happened.\" The Sculpture Garden was dedicated on October 13, 1995."),
    Location(sport: "Soccer", name: "Grant Park", coordinates: [45.538474, -122.628424], notes: "2 fields. Park hours: 5:00am-midnight.", address: "NE 33rd Avenue and US Grant Place Portland, OR 97212 United States", about: "Grant Park was the setting for many scenes in children's books by Beverly Cleary. In 1991, a group of teachers, librarians, and business people formed the Friends of Henry & Ramona, and began to raise funds for the Beverly Cleary Sculpture Garden for Children. Portland artist Lee Hunt created life-sized bronze statues of three of Cleary's best-loved characters - Ramona Quimby, Henry Huggins, and Henry's dog Ribsy. Scattered around the concrete slab are granite plaques engraved with the titles of the Cleary books that take place in Portland - and a map of the neighborhood showing where events in the books \"really happened.\" The Sculpture Garden was dedicated on October 13, 1995."),
    Location(sport: "Baseball", name: "Grant Park", coordinates: [45.538474, -122.628424], notes: "2 fields. Park hours: 5:00am-midnight.", address: "NE 33rd Avenue and US Grant Place Portland, OR 97212 United States", about: "Grant Park was the setting for many scenes in children's books by Beverly Cleary. In 1991, a group of teachers, librarians, and business people formed the Friends of Henry & Ramona, and began to raise funds for the Beverly Cleary Sculpture Garden for Children. Portland artist Lee Hunt created life-sized bronze statues of three of Cleary's best-loved characters - Ramona Quimby, Henry Huggins, and Henry's dog Ribsy. Scattered around the concrete slab are granite plaques engraved with the titles of the Cleary books that take place in Portland - and a map of the neighborhood showing where events in the books \"really happened.\" The Sculpture Garden was dedicated on October 13, 1995."),
    Location(sport: "Football", name: "Grant Park", coordinates: [45.538743, -122.629733], notes: "1 field. Park hours: 5:00am-midnight.", address: "NE 33rd Avenue and US Grant Place Portland, OR 97212 United States", about: "Grant Park was the setting for many scenes in children's books by Beverly Cleary. In 1991, a group of teachers, librarians, and business people formed the Friends of Henry & Ramona, and began to raise funds for the Beverly Cleary Sculpture Garden for Children. Portland artist Lee Hunt created life-sized bronze statues of three of Cleary's best-loved characters - Ramona Quimby, Henry Huggins, and Henry's dog Ribsy. Scattered around the concrete slab are granite plaques engraved with the titles of the Cleary books that take place in Portland - and a map of the neighborhood showing where events in the books \"really happened.\" The Sculpture Garden was dedicated on October 13, 1995."),
    Location(sport: "Soccer", name: "Harney Park", coordinates: [45.462494, -122.593217], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SE 67th Ave and Harney Street Portland, OR 97206 United States", about: "Portland Parks & Recreation, with support from Nike and the Portland Trail Blazers, has given the Harney Park basketball court a brand new look. This work was completed in July 2022."),
    Location(sport: "Baseball", name: "Harney Park", coordinates: [45.462494, -122.593217], notes: "2 fields. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SE 67th Ave and Harney Street Portland, OR 97206 United States", about: "Portland Parks & Recreation, with support from Nike and the Portland Trail Blazers, has given the Harney Park basketball court a brand new look. This work was completed in July 2022."),
    Location(sport: "Basketball", name: "Harney Park", coordinates: [45.462973, -122.594256], notes: "1 court. Park hours: 5:00am-midnight.", address: "SE 67th Ave and Harney Street Portland, OR 97206 United States", about: "Portland Parks & Recreation, with support from Nike and the Portland Trail Blazers, has given the Harney Park basketball court a brand new look. This work was completed in July 2022."),
    Location(sport: "Soccer", name: "Healy Heights Park", coordinates: [45.492852, -122.698409], notes: "Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "SW Patrick Pl & SW Council Crest Dr Portland, OR  97239 United States", about: ""),
    Location(sport: "Basketball", name: "Healy Heights Park", coordinates: [45.492838, -122.698813], notes: "Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "SW Patrick Pl & SW Council Crest Dr Portland, OR  97239 United States", about: ""),
    Location(sport: "Basketball", name: "Hillside Park", coordinates: [45.527533, -122.709413], notes: "Park hours: 5:00am-midnight", address: "Hillside Park 653 NW Culpepper Terr Portland, OR  97210 United States", about: "The parking lot closes at 8:30 pm on Monday through Thursday, and at 6:00 pm on Friday for the weekend. The parking lot gate reopens on Monday morning."),
    Location(sport: "Soccer", name: "Hillside Park", coordinates: [45.527520, -122.708737], notes: "Park hours: 5:00am-midnight", address: "Hillside Park 653 NW Culpepper Terr Portland, OR  97210 United States", about: "The parking lot closes at 8:30 pm on Monday through Thursday, and at 6:00 pm on Friday for the weekend. The parking lot gate reopens on Monday morning."),
    Location(sport: "Tennis", name: "Kenilworth Park", coordinates: [45.490920, -122.632312], notes: "2 courts. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SE 34th Avenue and Holgate Blvd Portland, OR 97202", about: "The land occupied by Kenilworth Park and most of the Kenilworth neighborhood was part of the land claim owned by Clinton Kelly, a Methodist minister from Kentucky who settled in the area in 1848. In 1909 the Portland Park Board purchased 9 acres from Kelly with funds from a 1908 bond measure created specifically to acquire land for parks in Portland. The park and the neighborhood, platted in 1889, are named after Sir Walter Scott's 1821 novel Kenilworth, a romantic novel set in Elizabethan England."),
    Location(sport: "Baseball", name: "Kenilworth Park", coordinates: [45.491388, -122.632259], notes: "Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SE 34th Avenue and Holgate Blvd Portland, OR 97202", about: "The land occupied by Kenilworth Park and most of the Kenilworth neighborhood was part of the land claim owned by Clinton Kelly, a Methodist minister from Kentucky who settled in the area in 1848. In 1909 the Portland Park Board purchased 9 acres from Kelly with funds from a 1908 bond measure created specifically to acquire land for parks in Portland. The park and the neighborhood, platted in 1889, are named after Sir Walter Scott's 1821 novel Kenilworth, a romantic novel set in Elizabethan England."),
    Location(sport: "Soccer", name: "Kenton Park", coordinates: [45.583153, -122.690226], notes: "1 field. Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "8417 N Brandon Avenue Portland, OR 97217", about: "In 2018, Kenton Park’s playground was fully renovated, including the addition of new accessibility features, with funding from the 2014 Parks Replacement Bond."),
    Location(sport: "Baseball", name: "Kenton Park", coordinates: [45.583153, -122.690226], notes: "2 fields. Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "8417 N Brandon Avenue Portland, OR 97217", about: "In 2018, Kenton Park’s playground was fully renovated, including the addition of new accessibility features, with funding from the 2014 Parks Replacement Bond."),
    Location(sport: "Basketball", name: "Kenton Park", coordinates: [45.582940, -122.691263], notes: "1 court. Park hours: 5:00am-midnight.", address: "8417 N Brandon Avenue Portland, OR 97217", about: "In 2018, Kenton Park’s playground was fully renovated, including the addition of new accessibility features, with funding from the 2014 Parks Replacement Bond."),
    Location(sport: "Baseball", name: "Kern Park", coordinates: [45.493746, -122.594983], notes: " 1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SE 67th Avenue and Center Street Portland, OR 97206", about: "According to Eugene E. Snyder's Portland Names and Neighborhoods, this park was named for the Kern Park real estate subdivision plat, laid out in 1903 by the Sycamore Real Estate Company."),
    Location(sport: "Basketball", name: "Kern Park", coordinates: [45.493191, -122.595050], notes: " 1 court. Park hours: 5:00am-midnight.", address: "SE 67th Avenue and Center Street Portland, OR 97206", about: "According to Eugene E. Snyder's Portland Names and Neighborhoods, this park was named for the Kern Park real estate subdivision plat, laid out in 1903 by the Sycamore Real Estate Company."),
    Location(sport: "Baseball", name: "Lents Park", coordinates: [45.488908, -122.570944], notes: "Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "SE 92nd Ave & Holgate Blvd Portland, OR 97266 United States", about: "Lents Park is named after Oliver Perry Lent, a stonemason who came to Oregon in the 1850s to farm a 190-acre land claim. The area became the center of a growing farm community. George P. Lent, the eldest son of Oliver Lent, platted the town of Lents in 1892. In 1912, the Lents community was annexed from Multnomah County and incorporated into the City of Portland."),
    Location(sport: "Soccer", name: "Lents Park", coordinates: [45.487410, -122.570751], notes: "1 pitch. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "SE 92nd Ave & Holgate Blvd Portland, OR 97266 United States", about: "Lents Park is named after Oliver Perry Lent, a stonemason who came to Oregon in the 1850s to farm a 190-acre land claim. The area became the center of a growing farm community. George P. Lent, the eldest son of Oliver Lent, platted the town of Lents in 1892. In 1912, the Lents community was annexed from Multnomah County and incorporated into the City of Portland."),
    Location(sport: "Basketball", name: "Lents Park", coordinates: [45.485929, -122.569473], notes: "2 courts. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "SE 92nd Ave & Holgate Blvd Portland, OR 97266 United States", about: "Lents Park is named after Oliver Perry Lent, a stonemason who came to Oregon in the 1850s to farm a 190-acre land claim. The area became the center of a growing farm community. George P. Lent, the eldest son of Oliver Lent, platted the town of Lents in 1892. In 1912, the Lents community was annexed from Multnomah County and incorporated into the City of Portland."),
    Location(sport: "Tennis", name: "Lents Park", coordinates: [45.485552, -122.569936], notes: "2 courts. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "SE 92nd Ave & Holgate Blvd Portland, OR 97266 United States", about: "Lents Park is named after Oliver Perry Lent, a stonemason who came to Oregon in the 1850s to farm a 190-acre land claim. The area became the center of a growing farm community. George P. Lent, the eldest son of Oliver Lent, platted the town of Lents in 1892. In 1912, the Lents community was annexed from Multnomah County and incorporated into the City of Portland."),
    Location(sport: "Basketball", name: "Luuwit View Park", coordinates: [45.550529, -122.529315], notes: "1 court. Park hours: 5:00am to midnight", address: "3546 NE 127th Ave Portland, OR  97230 United States", about: "Luuwit View Park offers expansive views, including a majestic vista of Luuwit, the Native (upper Cowlitz) name for Mt. St. Helens. The park’s name helps to honor the Indigenous people who have lived on the land since time immemorial and serves to recognize the overall history of the area."),
    Location(sport: "Soccer", name: "Luuwit View Park", coordinates: [45.549723, -122.530982], notes: "1 field. Park hours: 5:00am to midnight", address: "3546 NE 127th Ave Portland, OR  97230 United States", about: "Luuwit View Park offers expansive views, including a majestic vista of Luuwit, the Native (upper Cowlitz) name for Mt. St. Helens. The park’s name helps to honor the Indigenous people who have lived on the land since time immemorial and serves to recognize the overall history of the area."),
    Location(sport: "Baseball", name: "McKenna Park", coordinates: [45.581755, -122.732549], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "N Wall Avenue and Princeton Street Portland, OR 97203"),
    Location(sport: "Soccer", name: "McKenna Park", coordinates: [45.581755, -122.732549], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "N Wall Avenue and Princeton Street Portland, OR 97203"),
    Location(sport: "Basketball", name: "McKenna Park", coordinates: [45.581869, -122.733622], notes: "1 court. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "N Wall Avenue and Princeton Street Portland, OR 97203"),
    Location(sport: "Baseball", name: "Normandale Park", coordinates: [45.530806, -122.605888], notes: "Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "5700 NE Halsey St Portland, OR  97213 United States"),
    Location(sport: "Basketball", name: "Normandale Park", coordinates: [45.531757, -122.606687], notes: "1 court. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "5700 NE Halsey St Portland, OR  97213 United States"),
    Location(sport: "Football", name: "Normandale Park", coordinates: [45.532814, -122.606014], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "5700 NE Halsey St Portland, OR  97213 United States"),
    Location(sport: "Soccer", name: "Normandale Park", coordinates: [45.532814, -122.606014], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "5700 NE Halsey St Portland, OR  97213 United States"),
    Location(sport: "Volleyball", name: "Normandale Park", coordinates: [45.531669, -122.606928], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "5700 NE Halsey St Portland, OR  97213 United States"),
    Location(sport: "Tennis", name: "Northfate Park", coordinates: [45.589616, -122.724554], notes: "Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "9420 N Geneva Ave Portland, OR  97203 United States"),
    Location(sport: "Soccer", name: "Northfate Park", coordinates: [45.590306, -122.725671], notes: "1 pitch. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "9420 N Geneva Ave Portland, OR  97203 United States"),
    Location(sport: "Baseball", name: "Northfate Park", coordinates: [45.590306, -122.725671], notes: "2 fields. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "9420 N Geneva Ave Portland, OR  97203 United States"),
    Location(sport: "Baseball", name: "Overlook Park", coordinates: [45.548660, -122.682176], notes: "Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "1599 N Fremont St Portland, OR  97227 United States", about: "Created in 2021, the nature patch on the north slope at Overlook Park features forest understory, wildflower meadow, and high desert landscapes."),
    Location(sport: "Soccer", name: "Overlook Park", coordinates: [45.548660, -122.682176], notes: "Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "1599 N Fremont St Portland, OR  97227 United States", about: "Created in 2021, the nature patch on the north slope at Overlook Park features forest understory, wildflower meadow, and high desert landscapes."),
    Location(sport: "Basketball", name: "Overlook Park", coordinates: [45.548088, -122.682732], notes: "1 court. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "1599 N Fremont St Portland, OR  97227 United States", about: "Created in 2021, the nature patch on the north slope at Overlook Park features forest understory, wildflower meadow, and high desert landscapes."),
    Location(sport: "Baseball", name: "Pendleton Park", coordinates: [45.480429, -122.731564], notes: "1 field. Park hours: 5:00am-midnight", address: "SW 55th Avenue and Iowa Street Portland, OR 97221", about: "George H. Pendleton was a congressman from Ohio who, in 1864, ran for vice-president of the United States with McClellan against the ticket of Abraham Lincoln and Andrew Johnson. In 2001, a sculpture by Keith Jellum, Vincent, Waiting for Alice, was installed in the park. Inspired by Lewis Carroll's Alice in Wonderland, the piece includes an 8-foot-tall rabbit with a short table with a pair of gloves and a fan that the rabbit has misplaced."),
    Location(sport: "Soccer", name: "Pendleton Park", coordinates: [45.480429, -122.731564], notes: "1 field. Park hours: 5:00am-midnight", address: "SW 55th Avenue and Iowa Street Portland, OR 97221", about: "George H. Pendleton was a congressman from Ohio who, in 1864, ran for vice-president of the United States with McClellan against the ticket of Abraham Lincoln and Andrew Johnson. In 2001, a sculpture by Keith Jellum, Vincent, Waiting for Alice, was installed in the park. Inspired by Lewis Carroll's Alice in Wonderland, the piece includes an 8-foot-tall rabbit with a short table with a pair of gloves and a fan that the rabbit has misplaced."),
    Location(sport: "Baseball", name: "Pier Park", coordinates: [45.603801, -122.758685], notes: "4 fields. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "10325 N Lombard St Portland, OR  97203 United States", about: "The park was named for Stanhope S. Pier, who served as a Portland city commissioner in the late 1920s and as acting mayor in 1931. In 1930, Commissioner Pier proposed several improvements, including a pool in Albina, the expansion of Mt Scott and Lents Parks, and the development of Pier Park in the style of Laurelhurst, then considered the most beautiful park in the city."),
    Location(sport: "Tennis", name: "Pier Park", coordinates: [45.601291, -122.753432], notes: "2 courts. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "10325 N Lombard St Portland, OR  97203 United States", about: "The park was named for Stanhope S. Pier, who served as a Portland city commissioner in the late 1920s and as acting mayor in 1931. In 1930, Commissioner Pier proposed several improvements, including a pool in Albina, the expansion of Mt Scott and Lents Parks, and the development of Pier Park in the style of Laurelhurst, then considered the most beautiful park in the city."),
    Location(sport: "Basketball", name: "Pier Park", coordinates: [45.601291, -122.753432], notes: "1 court. Park hours: 5:00am-midnight. To reserve a sports field or picnic area, call 503-823-2525.", address: "10325 N Lombard St Portland, OR  97203 United States", about: "The park was named for Stanhope S. Pier, who served as a Portland city commissioner in the late 1920s and as acting mayor in 1931. In 1930, Commissioner Pier proposed several improvements, including a pool in Albina, the expansion of Mt Scott and Lents Parks, and the development of Pier Park in the style of Laurelhurst, then considered the most beautiful park in the city."),
    Location(sport: "Baseball", name: "Portland Heights Park", coordinates: [45.504682, -122.707625], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SW Patton Road and Old Orchard Road Portland, OR 97201", about: "In the 1920s, this property was owned by Mayannah and Boudinot Seeley who allowed neighbors in the area to use it for games and recreation. In 1924, the Portland Heights Club presented a preliminary plan to the City for the development of the site, including a ball field, tennis courts, and restrooms. The City built a playground between 1925-27; it was operated by the Portland Heights Playground Association (PHPA). In 1929, the Seeleys sold the property to the PHPA who raised funds for the purchase by subscription. In 1943, the site was deeded to the City."),
    Location(sport: "Soccer", name: "Portland Heights Park", coordinates: [45.504682, -122.707625], notes: "1 field. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SW Patton Road and Old Orchard Road Portland, OR 97201", about: "In the 1920s, this property was owned by Mayannah and Boudinot Seeley who allowed neighbors in the area to use it for games and recreation. In 1924, the Portland Heights Club presented a preliminary plan to the City for the development of the site, including a ball field, tennis courts, and restrooms. The City built a playground between 1925-27; it was operated by the Portland Heights Playground Association (PHPA). In 1929, the Seeleys sold the property to the PHPA who raised funds for the purchase by subscription. In 1943, the site was deeded to the City."),
    Location(sport: "Basketball", name: "Portland Heights Park", coordinates: [45.504314, -122.708004], notes: "1 court. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SW Patton Road and Old Orchard Road Portland, OR 97201", about: "In the 1920s, this property was owned by Mayannah and Boudinot Seeley who allowed neighbors in the area to use it for games and recreation. In 1924, the Portland Heights Club presented a preliminary plan to the City for the development of the site, including a ball field, tennis courts, and restrooms. The City built a playground between 1925-27; it was operated by the Portland Heights Playground Association (PHPA). In 1929, the Seeleys sold the property to the PHPA who raised funds for the purchase by subscription. In 1943, the site was deeded to the City."),
    Location(sport: "Tennis", name: "Portland Heights Park", coordinates: [45.503951, -122.708036], notes: "2 courts. Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SW Patton Road and Old Orchard Road Portland, OR 97201", about: "In the 1920s, this property was owned by Mayannah and Boudinot Seeley who allowed neighbors in the area to use it for games and recreation. In 1924, the Portland Heights Club presented a preliminary plan to the City for the development of the site, including a ball field, tennis courts, and restrooms. The City built a playground between 1925-27; it was operated by the Portland Heights Playground Association (PHPA). In 1929, the Seeleys sold the property to the PHPA who raised funds for the purchase by subscription. In 1943, the site was deeded to the City."),
    Location(sport: "Baseball", name: "Powell Park", coordinates: [45.498084, -122.642390], notes: "Park hours: 5:00am-midnight To reserve a sports field or picnic area, call 503-823-2525.", address: "SE 26th Avenue and Powell Blvd Portland, OR 97202"),
    Location(sport: "Soccer", name: "Powell Park", coordinates: [45.498084, -122.642390], notes: "Park hours: 5:00am-midnight To reserve a sports field or picnic area, call 503-823-2525.", address: "SE 26th Avenue and Powell Blvd Portland, OR 97202"),
    Location(sport: "Basketball", name: "Powell Park", coordinates: [45.497646, -122.640106], notes: "1 court. Park hours: 5:00am-midnight To reserve a sports field or picnic area, call 503-823-2525.", address: "SE 26th Avenue and Powell Blvd Portland, OR 97202"),
    Location(sport: "Tennis", name: "Rose City Park", coordinates: [45.538638, -122.598499], notes: "2 lighted courts. Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "NE 62nd Avenue and Tillamook Street Portland, OR 97213"),
    Location(sport: "Baseball", name: "Rose City Park", coordinates: [45.538638, -122.598499], notes: "2 fields. Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "NE 62nd Avenue and Tillamook Street Portland, OR 97213"),
    Location(sport: "Soccer", name: "Rose City Park", coordinates: [45.538638, -122.598499], notes: "1 field. Park hours: 5:00am-midnight To reserve a sports field, call 503-823-2525.", address: "NE 62nd Avenue and Tillamook Street Portland, OR 97213"),
    Location(sport: "Baseball", name: "Sellwood Park", coordinates: [45.468475, -122.660238], notes: "2 fields. Park hours: 5:00am-midnight. Parking lot closed at 10:00pm. To reserve a sports field or picnic area, call 503-823-2525", address: "SE Seventh Ave Portland, OR 97202 United States", about: "In 1893, the town of Sellwood was merged into Portland, but has managed to keep its own identity throughout the years. The area is named for John Sellwood, an Episcopal minister who owned the land claim in what is now the Sellwood area. Sellwood Park used to be the site of the City View Racetrack."),
    Location(sport: "Football", name: "Sellwood Park", coordinates: [45.468475, -122.660238], notes: "1 field. Park hours: 5:00am-midnight. Parking lot closed at 10:00pm. To reserve a sports field or picnic area, call 503-823-2525", address: "SE Seventh Ave Portland, OR 97202 United States", about: "In 1893, the town of Sellwood was merged into Portland, but has managed to keep its own identity throughout the years. The area is named for John Sellwood, an Episcopal minister who owned the land claim in what is now the Sellwood area. Sellwood Park used to be the site of the City View Racetrack."),
    Location(sport: "Soccer", name: "Sellwood Park", coordinates: [45.468475, -122.660238], notes: "1 field. Park hours: 5:00am-midnight. Parking lot closed at 10:00pm. To reserve a sports field or picnic area, call 503-823-2525", address: "SE Seventh Ave Portland, OR 97202 United States", about: "In 1893, the town of Sellwood was merged into Portland, but has managed to keep its own identity throughout the years. The area is named for John Sellwood, an Episcopal minister who owned the land claim in what is now the Sellwood area. Sellwood Park used to be the site of the City View Racetrack."),
    Location(sport: "Tennis", name: "Sellwood Park", coordinates: [45.466472, -122.660690], notes: "4 courts. Park hours: 5:00am-midnight. Parking lot closed at 10:00pm. To reserve a sports field or picnic area, call 503-823-2525", address: "SE Seventh Ave Portland, OR 97202 United States", about: "In 1893, the town of Sellwood was merged into Portland, but has managed to keep its own identity throughout the years. The area is named for John Sellwood, an Episcopal minister who owned the land claim in what is now the Sellwood area. Sellwood Park used to be the site of the City View Racetrack."),
    Location(sport: "Baseball", name: "Sewallcrest Park", coordinates: [45.509558, -122.632941], notes: "Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SE 31st Avenue and Market Street Portland, OR 97214 United States"),
    Location(sport: "Soccer", name: "Sewallcrest Park", coordinates: [45.509558, -122.632941], notes: "Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SE 31st Avenue and Market Street Portland, OR 97214 United States"),
    Location(sport: "Basketball", name: "Sewallcrest Park", coordinates: [45.509558, -122.632941], notes: "Park hours: 5:00am-midnight. To reserve a sports field, call 503-823-2525.", address: "SE 31st Avenue and Market Street Portland, OR 97214 United States"),
    Location(sport: "Basketball", name: "Sunnyside School Park", coordinates: [45.515273, -122.628986], notes: "Park hours: 5:00am-10:00pm", address: "SE 34th Ave & SE Taylor St Portland, OR  97214 United States"),
    Location(sport: "Soccer", name: "Sunnyside School Park", coordinates: [45.515273, -122.628986], notes: "Park hours: 5:00am-10:00pm", address: "SE 34th Ave & SE Taylor St Portland, OR  97214 United States"),
    Location(sport: "Baseball", name: "Unthank Park", coordinates: [45.551423, -122.671202], notes: "1 feild. Park hours: 5:00am-midnight", address: "510 N Shaver Street Portland, OR 97227", about: "Includes accessible restroom, baseball field, basketball court, paths - paved, picnic tables, and playground."),
    Location(sport: "Basketball", name: "Unthank Park", coordinates: [45.551423, -122.671202], notes: "2 courts. Park hours: 5:00am-midnight", address: "510 N Shaver Street Portland, OR 97227", about: "Includes accessible restroom, baseball field, basketball court, paths - paved, picnic tables, and playground."),
    Location(sport: "Soccer", name: "Wallace Park", coordinates: [45.533254, -122.703815], notes: "1 field. Park hours: 5:00am-midnight. To reserve a picnic area or sports field, call 503-823-2525.", address: "NW Raleigh St & NW 25th Ave Portland, OR  97210 United States", about: "This park is named for Hugh W. Wallace, the city councilman responsible for getting the property allocated as a city park. A search of the park and school yard will reveal a curious collection of 11 bronze objects tucked away in unexpected places. Entitled Eleven Very Small Sculptures, they were created by artist Bill Will in 1998. Another art installation in the park is a 1980 sculpture by Manuel Izquierdo called Silver Dawn. Izquierdo is professor emeritus of Pacific Northwest College of Art."),
    Location(sport: "Baseball", name: "Wallace Park", coordinates: [45.533254, -122.703815], notes: "2 fields. Park hours: 5:00am-midnight. To reserve a picnic area or sports field, call 503-823-2525.", address: "NW Raleigh St & NW 25th Ave Portland, OR  97210 United States", about: "This park is named for Hugh W. Wallace, the city councilman responsible for getting the property allocated as a city park. A search of the park and school yard will reveal a curious collection of 11 bronze objects tucked away in unexpected places. Entitled Eleven Very Small Sculptures, they were created by artist Bill Will in 1998. Another art installation in the park is a 1980 sculpture by Manuel Izquierdo called Silver Dawn. Izquierdo is professor emeritus of Pacific Northwest College of Art."),
    Location(sport: "Basketball", name: "Wallace Park", coordinates: [45.533254, -122.703815], notes: "1 court. Park hours: 5:00am-midnight. To reserve a picnic area or sports field, call 503-823-2525.", address: "NW Raleigh St & NW 25th Ave Portland, OR  97210 United States", about: "This park is named for Hugh W. Wallace, the city councilman responsible for getting the property allocated as a city park. A search of the park and school yard will reveal a curious collection of 11 bronze objects tucked away in unexpected places. Entitled Eleven Very Small Sculptures, they were created by artist Bill Will in 1998. Another art installation in the park is a 1980 sculpture by Manuel Izquierdo called Silver Dawn. Izquierdo is professor emeritus of Pacific Northwest College of Art."),
    Location(sport: "Tennis", name: "Westmoreland Park", coordinates: [45.473781, -122.640805], notes: "2 courts. Park hours: 5:00am-midnight To reserve a sports field or picnic area, call 503-823-2525.", address: "SE McLoughlin Blvd Portland, OR 97202 United States"),
    Location(sport: "Baseball", name: "Westmoreland Park", coordinates: [45.471026, -122.640939], notes: "5 fields. Park hours: 5:00am-midnight To reserve a sports field or picnic area, call 503-823-2525.", address: "SE McLoughlin Blvd Portland, OR 97202 United States"),
    Location(sport: "Football", name: "Westmoreland Park", coordinates: [45.471026, -122.640939], notes: "1 field. Park hours: 5:00am-midnight To reserve a sports field or picnic area, call 503-823-2525.", address: "SE McLoughlin Blvd Portland, OR 97202 United States"),
    Location(sport: "Soccer", name: "Westmoreland Park", coordinates: [45.471026, -122.640939], notes: "1 field. Park hours: 5:00am-midnight To reserve a sports field or picnic area, call 503-823-2525.", address: "SE McLoughlin Blvd Portland, OR 97202 United States"),
    Location(sport: "Basketball", name: "Westmoreland Park", coordinates: [45.468765, -122.641154], notes: "1 field. Park hours: 5:00am-midnight To reserve a sports field or picnic area, call 503-823-2525.", address: "SE McLoughlin Blvd Portland, OR 97202 United States"),
    Location(sport: "Tennis", name: "Willamette Park", coordinates: [45.474220, -122.670371], notes: "4 courts. 5:00am-10:00pm, Closed to vehicles at 10:00pm", address: "SW Macadam Avenue and Nebraska Street Portland, OR 97219 United States"),
    Location(sport: "Soccer", name: "Willamette Park", coordinates: [45.474751, -122.669609], notes: "2 fields. 5:00am-10:00pm, Closed to vehicles at 10:00pm", address: "SW Macadam Avenue and Nebraska Street Portland, OR 97219 United States"),
    Location(sport: "Soccer", name: "Wilshire Park", coordinates: [45.552949, -122.628108], notes: "1 field. Park hours: 5:00am-midnight", address: "3460–3538 NE Skidmore St Portland, OR  97211 United States"),
    Location(sport: "Baseball", name: "Wilshire Park", coordinates: [45.552949, -122.628108], notes: "2 fields. Park hours: 5:00am-midnight", address: "3460–3538 NE Skidmore St Portland, OR  97211 United States"),
    Location(sport: "Volleyball", name: "Wilshire Park", coordinates: [45.552949, -122.628108], notes: "2 fields. Park hours: 5:00am-midnight", address: "3460–3538 NE Skidmore St Portland, OR  97211 United States"),
]

